version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    container_name: stadtarchiv-flask
    volumes:
      - .:/app
    networks:
      stadtarchiv:
        aliases:
        - flask
    entrypoint: ["python3", "runserver.py"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: stadtarchiv-worker
    volumes:
      - .:/app
    networks:
      stadtarchiv:
        aliases:
        - worker
    entrypoint: ["/app/celery.sh"]

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    container_name: stadtarchiv-webpack
    ports:
      - 8888:8888
    volumes:
      - .:/app
      - stadtarchiv_node_modules:/app/node_modules
    networks:
      stadtarchiv:
        aliases:
        - webpack
    entrypoint: ["/app/webpack.sh"]

  rabbitmq:
    image: rabbitmq:latest
    container_name: stadtarchiv-rabbitmq
    networks:
      stadtarchiv:
        aliases:
        - rabbitmq

  mongodb:
    image: mongo:4.2
    container_name: stadtarchiv-mongodb
    volumes:
      - .:/app
    networks:
      stadtarchiv:
        aliases:
        - mongodb

  memcached:
    image: memcached:latest
    container_name: stadtarchiv-memcached
    networks:
      stadtarchiv:
        aliases:
        - memcached

  minio:
    image: minio/minio
    container_name: stadtarchiv-minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=DEVELOPMENT
      - MINIO_SECRET_KEY=DEVELOPMENT
    volumes:
      - stadtarchiv_minio:/data
    networks:
      stadtarchiv:
        aliases:
        - minio
    command: server /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: stadtarchiv-elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      stadtarchiv:
        aliases:
        - elasticsearch


volumes:
  stadtarchiv_node_modules:
  stadtarchiv_minio:

networks:
  stadtarchiv: