version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    container_name: stadtarchiv-flask
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
      - minio
      - elasticsearch
    entrypoint: ["python3", "runserver.py"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: stadtarchiv-worker
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb
    entrypoint: ["celery", "-A", "webapp.celery_entry_point", "worker"]

  gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    container_name: stadtarchiv-gulp
    volumes:
      - .:/app
      - stadtarchiv_node_modules:/app/node_modules
    entrypoint: ["gulp", 'watch']

  redis:
    image: redis
    container_name: stadtarchiv-redis

  mongodb:
    image: mongo:3.6
    container_name: stadtarchiv-mongodb

  minio:
    image: minio/minio
    container_name: stadtarchiv-minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=DEVELOPMENT
      - MINIO_SECRET_KEY=DEVELOPMENT
    volumes:
      - stadtarchiv_minio:/data
    command: server /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: stadtarchiv-elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1


volumes:
  stadtarchiv_node_modules:
  stadtarchiv_mysql:
  stadtarchiv_minio: